### ISSUE TITLE
Module '"kit-query-params"' has no exported member 'queryParams'.

### ISSUE THREAD

**Issue by kallaviktor** [beynar/kit-query-params#3]
Hi,

First I would like to thank you for your work, it seems that's what I'm struggling with for a week now by implementing myself using a GET/POST form, but could not figure out the correct solution yet.

So I tried to follow the readme, but I'm not sure you are referring to the correct import:

`import { queryParams } from 'kit-query-params';` results in ` Module '"kit-query-params"' has no exported member 'queryParams'.` however works with `import { queryParamsState } from 'kit-query-params';`

I also tried to define default values, but it's not working, it's possible that I'm doing something wrong:

+page.svelte
```
const params = queryParamsState({
		schema: {
			search: 'string',
			page: 'string',
			limit: 'string',
			destinations: ['number']
		},
		default: {
			page: '1',
			limit: '5'
		}
});
```

+page.server.ts
```
const filterParams = parseURL(url, {
		search: 'string',
		page: 'string',
		limit: 'string',
		destinations: ['number']
});

console.log(filterParams);

{ search: null, page: null, limit: null, destinations: [] }
```

I also would like to know if it's possible to change debounce and fire URL change on a button click?

Thank you so much!

**Comment by beynar** [comment]
Hello sorry for that the readme was not up to date

**Comment by kallaviktor** [comment]
Can you comment on the default value issue please?

**Comment by beynar** [comment]
Yeah I did'nt read the whole comment, long day here ✌️

So when you define default values they will populate the value returned by the state. So in the +page.svelte when the state is initialized and no query params are found in the url `params.page` will be "1" and `params.limit` will be "5". 
In your +server.ts you can also pass default values as a third parameter of the parseURL function (maybe upgrade to 0.0.25 i'm not sure about previous versions)

The idea of a manual trigger is actually quite nice, I will work on it very soon, thank you 🙏

**Comment by beynar** [comment]
Ok it was easy, I just pushed an update `kit-query-params@0.0.26` to disable the debounce and manually sync the url with the state

**Comment by kallaviktor** [comment]
Very nice! Thank you!

However I still dont get the point of defining default on client side as it wont get posted to the server. If I define default on server side it overwrites whats arriving from the client.
